### ISSUE TITLE
No kvo of selectedIndex when scrollViewDidEndDecelerating

### ISSUE THREAD

**Issue by tomisacat** [zhangao0086/DKTabPageViewController#22]
I noticed that the scrollView delegate method `scrollViewDidEndDecelerating:` in DKTabPageViewController.m (the last one method of that file) you set selectedIndex by `setSelectedIndexByIndex:` , in which it loses kvo for `selectedIndex` property, I need it because I have to use it in a two-way binding so I modified it as like:
~~~objective-c
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView{
    NSInteger newIndex = scrollView.contentOffset.x / CGRectGetWidth(scrollView.bounds);
    if (self.selectedIndex != newIndex) {
        [self willChangeValueForKey:NSStringFromSelector(@selector(selectedIndex))];
        [self setSelectedIndexByIndex:newIndex];
        [self didChangeValueForKey:NSStringFromSelector(@selector(selectedIndex))];
    }
}
~~~
Feel free to use it : ). Really appreaciate your great work, it helps me a lot!

**Comment by zhangao0086** [comment]
Hello @tomisacat 

Why not using `pageChangedBlock`?

**Comment by tomisacat** [comment]
@zhangao0086 I have another control which UI depends on the `selectedIndex` and also it will influence the `selectedIndex` of tabPageViewController if changed (In shortly, I make them two-way binding), so I wanna observe the `selectedIndex` changes. I prefer this a better solution for me instead of use `pageChangedBlock` .

**Comment by zhangao0086** [comment]
@tomisacat I will quickly adding support for KVO as you say and bumping version to **1.4.1**.
Thanks for your support :)

**Comment by tomisacat** [comment]
@zhangao0086 Thanks!
